@startuml CapNhatNguoiDung_UC
left to right direction
actor "Admin" as admin

rectangle "Cập nhật thông tin người dùng" {
  usecase "Cập nhật hồ sơ tài khoản" as UC_Update
}

admin --> UC_Update
@enduml
