@startuml QuanLyUngVienTrongBauCu_UC
left to right direction
actor "Admin" as admin

rectangle "Quản lý ứng viên trong cuộc bầu cử" {
  usecase "Thêm ứng viên" as UC_Add
  usecase "Xóa ứng viên" as UC_Delete
}

admin --> UC_Add
admin --> UC_Delete
note "Chỉ áp dụng khi\ncuộc bầu cử ở trạng thái PENDING" as N_Pending
N_Pending .. UC_Add
N_Pending .. UC_Delete
@enduml
