@startuml QuanLyTrangThaiTaiKhoan_UC
left to right direction
actor "Admin" as admin

rectangle "Quản lý trạng thái tài khoản" {
  usecase "Vô hiệu hóa tài khoản" as UC_Disable
  usecase "Kích hoạt tài khoản" as UC_Enable
}

admin --> UC_Disable
admin --> UC_Enable
@enduml
