@startuml SaoLuuKhoaBiMat_UC
left to right direction
actor "Cử tri" as voter

rectangle "Sao lưu khóa bí mật phiếu" {
  usecase "Sao lưu khóa bí mật phiếu" as UC_Backup
}

voter --> UC_Backup
@enduml
