@startuml TimKiemCuocBauCu_UC
left to right direction
actor "Admin" as admin

rectangle "Tìm kiếm cuộc bầu cử" {
  usecase "Quản lý cuộc bầu cử" as UC_Manage
  usecase "Tìm kiếm và lọc cuộc bầu cử" as UC_Search
}

admin --> UC_Manage
UC_Search .> UC_Manage : <<extend>>
@enduml
