@startuml TimKiemNguoiDung
left to right direction
actor "Admin" as admin

rectangle "Tìm kiếm người dùng" {
  usecase "Quản lý người dùng" as UC_ManageUser
  usecase "Tìm kiếm và lọc người dùng" as UC_FilterUsers
}

admin --> UC_ManageUser

UC_FilterUsers .> UC_ManageUser : <<extend>>
@enduml
