@startuml TimKiemCuocBauCu_UC
left to right direction
skinparam packageStyle rectangle

actor "Admin" as admin

usecase "Đăng nhập hệ thống" as UC_Login
usecase "Quản lý cuộc bầu cử" as UC_Manage
usecase "Tìm kiếm và lọc cuộc bầu cử" as UC_Search

admin --> UC_Manage
UC_Manage ..> UC_Login : <<include>>
UC_Search .> UC_Manage : <<extend>>
@enduml
