@startuml XemThongTinNguoiDung_UC
left to right direction
skinparam packageStyle rectangle

actor "Admin" as admin

usecase "Đăng nhập hệ thống" as UC_Login
usecase "Quản lý người dùng" as UC_ManageUser

rectangle "Xem thông tin chi tiết người dùng" {
  usecase "Xem thông tin tài khoản" as UC_ViewAccount
  usecase "Xem lịch sử cuộc bầu cử của người dùng" as UC_ViewHistory
}

admin --> UC_ManageUser
UC_ManageUser ..> UC_Login : <<include>>

UC_ViewAccount .> UC_ManageUser : <<extend>>
UC_ViewHistory ..> UC_ViewAccount : <<include>>
@enduml
