@startuml XemBauCuCuaToi_UC
left to right direction
actor "Voter" as voter

rectangle "Xem danh sách cuộc bầu cử của cử tri" {
  usecase "Xem danh sách cuộc bầu cử đang tham gia" as UC_ListMine
  usecase "Lọc cuộc bầu cử theo trạng thái" as UC_Filter
}

voter --> UC_ListMine
UC_Filter .> UC_ListMine : <<extend>>
@enduml
