@startuml XemDanhSachPhieu_UC
left to right direction
actor "Admin" as admin

rectangle "Xem danh sách phiếu trong cuộc bầu cử" {
  usecase "Xem danh sách phiếu trong cuộc bầu cử" as UC_ViewVotes
  usecase "Lọc và phân trang danh sách phiếu" as UC_Filter
}

admin --> UC_ViewVotes
UC_ViewVotes <.. UC_Filter : <<extend>>
@enduml
