@startuml XemThongTinCaNhan_UC
left to right direction
actor "Admin" as admin
actor "Voter" as voter

rectangle "Xem thông tin tài khoản cá nhân" {
  usecase "Xem thông tin cá nhân" as UC_ViewProfile
}

admin --> UC_ViewProfile
voter --> UC_ViewProfile
@enduml
